# Site settings
name: Daniel McCann
description: 'Art-Oriented Graphics Engineer'

baseurl: '' # the subpath of your site, e.g. /blog
url: 'mccannd.github.io' # the base hostname & protocol for your site

# Build settings
markdown:            kramdown
relative_permalinks: false
permalink:           :title/

pagination:          true
paginate:            8
paginate_path:       page/:num/

author:
    name: 'Daniel McCann'
    email: 'danjm30@gmail.com'
    uri: 'https://github.com/mccannd'

sass:
    sass_dir: _sass
    style:    compressed

defaults:
  -
      scope:
        path: '_posts'
        type: 'posts'
      values:
        reading_time: true
        # Meta
        show_tags: true
        show_categories: true
        # Social
        share_buttons: false
        disqus: false

gems:
    - jekyll-feed
    - jekyll-sitemap
